name: ManualBuild

on:
  workflow_dispatch:
    inputs:
      datasource:
        description: Datasource Version
        required: true
        default: 0.0.5
      panel:
        description: Panel Version
        required: true
        default: 0.0.3
      latest:
        description: Push as latest
        required: true
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Image
        run: docker build --build-arg deep_datasource_version=${{  github.event.inputs.datasource }} --build-arg deep_datasource_panel=${{ github.event.inputs.panel }} -f Dockerfile -t intergral/grafana-deep:D${{ github.event.inputs.datasource }}P${{ github.event.inputs.panel }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image
        run: |
          docker push intergral/grafana-deep:D${{ github.event.inputs.datasource }}P${{ github.event.inputs.panel }}

      - name: Push Latest
        if: github.event.inputs.latest != false
        run: |
          docker tag intergral/grafana-deep:D${{ github.event.inputs.datasource }}P${{ github.event.inputs.panel }} intergral/grafana-deep:latest
          docker push intergral/grafana-deep:latest
