name: Release

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Image
        run: docker build --build-arg deep_datasource_version=${{ github.ref_name }} --build-arg deep_datasource_panel=${{ github.ref_name }} -f Dockerfile -t intergral/grafana-deep:${{ github.ref_name }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image
        run: |
          docker tag intergral/grafana-deep:${{ github.ref_name }} intergral/grafana-deep:latest
          docker push intergral/grafana-deep:${{ github.ref_name }}
          docker push intergral/grafana-deep:latest
